### PR TITLE
Fixed clippy warning `uninlined_format_args`

### LINKED ISSUE #47: Fix clippy warning: `uninlined_format_args`
With the newest version of clippy, a new lint was added: `uninlined_format_args`

Please remove the `#[allow(clippy:uninlined_format_args)]` directives from the `tockloader-cli/src/display.rs` file, and refactor the code such that clippy is happy.

### PR DESCRIPTION
**Pull request by AliwiWalid**
### Pull Request Overview

This pull request fixes clippy's `uninlined_format_args` by removing  the `#[allow(clippy:uninlined_format_args)]` directives from the tockloader-cli/src/display.rs file.

### TODO or Help Wanted

N/A

#### Using Rust tooling
- [x] Ran `cargo fmt`
- [x] Ran `cargo clippy`
- [x] Ran `cargo test`
- [x] Ran `cargo build`

### GitHub Issue

This pull request closes #47

### CODE REVIEW

File: tockloader-cli/src/display.rs [hunk 1]
```diff
@@ -5,234 +5,226 @@
...
         );
 
         println!(
-            " \x1b[1;32m Enabled:             {}",
-            details.tbf_header.enabled()
+            " {BOLD_GREEN} Enabled:          {RESET}{}",
+            details.tbf_header.enabled(),
         );
 
+        // Fixed typo: "Stricky" changed to "Sticky"
```
Comment (george-cosma) [inline tockloader-cli/src/display.rs:68]: Please remove this comment. You can mention it in the PR description.

**Comment by AliwiWalid** [comment]
@george-cosma ok now everything should be good

**Comment by AliwiWalid** [comment]
@george-cosma should be good now i hope

**Review by george-cosma — APPROVED** [review]

**Comment by george-cosma** [comment]
Also, I didn't ask but at this point it's a bit late since i merged, did you test out the code on hardware to see if it's all okay @AliwiWalid?  :))
